//
//  SnappThemingImage+Extensions.swift
//  SnappTheming
//
//  Created by Oleksii Kolomiiets on 24.02.2025.
//

import SwiftUI

#if canImport(UIKit)
    import UIKit
#elseif canImport(AppKit)
    import AppKit
#endif

extension SnappThemingImage {
    /// Converts `SnappThemingImage` to a SwiftUI `Image` representation.
    var image: Image {
        #if canImport(UIKit)
            return Image(uiImage: self)
        #elseif canImport(AppKit)
            return Image(nsImage: self)
        #endif
    }

    /// Creates a system image using the given system name.
    ///
    /// - Parameter systemName: The name of the system image (e.g., `"gear"`, `"heart.fill"`).
    /// - Returns: A `SnappThemingImage` (either `UIImage` or `NSImage`) if available, otherwise `nil`.
    ///
    /// - Note: On **macOS**, the accessibility description is automatically generated by replacing `.` with spaces
    ///   and capitalizing each word. For example, `"heart.fill"` becomes `"Heart Fill"`, improving readability.
    static func system(_ systemName: String) -> SnappThemingImage? {
        #if canImport(UIKit)
            return UIImage(systemName: systemName)
        #elseif canImport(AppKit)
            let description = systemName.replacingOccurrences(of: ".", with: " ").capitalized
            return NSImage(systemSymbolName: systemName, accessibilityDescription: description)
        #endif
    }
}
